// src/utils/translate.js

export const translations = {
  en: {
    title: "Create your personal video clip",
    subtitle: "Here you can create a musical greeting video or confess your feelings with a music video.",
    has_qr: "Do you already have a QR code?",
    yes: "Yes",
    no: "No",
    enter_qr: "Enter your QR code",
    continue: "Continue",
    buy: "Buy for $10",
    buy_link: "https://gumroad.com/l/wishclip",
    voice_title: "How should your clip sing?",
    ai_voice: "AI Voice",
    my_voice: "My Voice",
    voice_prompt: "Record 10-20 seconds of speech or singing in your language: 'Hi, I'm Alex. This is a song for Masha!'",
    upload_voice: "Record or upload your voice",
    voice_tip: "You can record your voice in any language — Kazakh, Ukrainian, Armenian, etc. The song will be created in your language."
  },
  ru: {
    title: "Создай персональный видеоклип",
    subtitle: "Здесь ты можешь создать музыкальное видео-поздравление или признаться кому-то в чувствах с помощью музыкального клипа.",
    has_qr: "У тебя уже есть QR?",
    yes: "Да",
    no: "Нет",
    enter_qr: "Введите или загрузите QR-код",
    continue: "Продолжить",
    buy: "Купить за $10",
    buy_link: "https://gumroad.com/l/wishclip",
    voice_title: "Как должен петь ваш клип?",
    ai_voice: "Голос ИИ",
    my_voice: "Мой голос",
    voice_prompt: "Запишите 10-20 секунд речи или пения на вашем языке: «Привет, меня зовут Алекс. Это песня для Маши!»",
    upload_voice: "Запишите или загрузите свой голос",
    voice_tip: "Вы можете записать голос на любом языке — казахском, украинском, армянском и др. Песня будет создана на вашем языке."
  },
  es: {
    title: "Crea tu videoclip personal",
    subtitle: "Crea un video musical de felicitación o declárate con un videoclip.",
    has_qr: "¿Ya tienes un código QR?",
    yes: "Sí",
    no: "No",
    enter_qr: "Ingresa tu código QR",
    continue: "Continuar",
    buy: "Comprar por $10",
    buy_link: "https://gumroad.com/l/wishclip",
    voice_title: "¿Cómo debería cantar tu clip?",
    ai_voice: "Voz de IA",
    my_voice: "Mi voz",
    voice_prompt: "Graba 10-20 segundos de habla o canto en tu idioma: 'Hola, soy Alex. ¡Esta es una canción para Masha!'",
    upload_voice: "Graba o sube tu voz",
    voice_tip: "Puedes grabar tu voz en cualquier idioma: kazajo, ucraniano, armenio, etc. La canción se creará en tu idioma."
  },
  de: {
    title: "Erstellen Sie Ihren persönlichen Videoclip",
    subtitle: "Erstellen Sie ein musikalisches Grußvideo oder gestehen Sie Ihre Gefühle mit einem Musikvideo.",
    has_qr: "Haben Sie bereits einen QR-Code?",
    yes: "Ja",
    no: "Nein",
    enter_qr: "Geben Sie Ihren QR-Code ein",
    continue: "Weiter",
    buy: "Kaufen für 10 $",
    buy_link: "https://gumroad.com/l/wishclip",
    voice_title: "Wie soll dein Clip singen?",
    ai_voice: "KI-Stimme",
    my_voice: "Meine Stimme",
    voice_prompt: "Nehmen Sie 10–20 Sekunden Sprache oder Gesang in Ihrer Sprache auf: 'Hallo, ich bin Alex. Dies ist ein Lied für Masha!'",
    upload_voice: "Stimme aufnehmen oder hochladen",
    voice_tip: "Sie können Ihre Stimme in jeder Sprache aufnehmen – Kasachisch, Ukrainisch, Armenisch usw. Der Song wird in Ihrer Sprache erstellt."
  },
  fr: {
    title: "Créez votre clip vidéo personnalisé",
    subtitle: "Créez une vidéo musicale de félicitation ou déclarez votre amour avec un clip.",
    has_qr: "Avez-vous déjà un code QR ?",
    yes: "Oui",
    no: "Non",
    enter_qr: "Saisissez votre code QR",
    continue: "Continuer",
    buy: "Acheter pour 10 $",
    buy_link: "https://gumroad.com/l/wishclip",
    voice_title: "Comment votre clip doit-il chanter ?",
    ai_voice: "Voix IA",
    my_voice: "Ma voix",
    voice_prompt: "Enregistrez 10 à 20 secondes de parole ou de chant dans votre langue : 'Salut, je suis Alex. C'est une chanson pour Masha !'",
    upload_voice: "Enregistrez ou téléversez votre voix",
    voice_tip: "Vous pouvez enregistrer votre voix dans n'importe quelle langue — kazakhe, ukrainienne, arménienne, etc. La chanson sera créée dans votre langue."
  },
  it: {
    title: "Crea il tuo videoclip personale",
    subtitle: "Crea un video musicale di auguri o dichiarati con un videoclip.",
    has_qr: "Hai già un codice QR?",
    yes: "Sì",
    no: "No",
    enter_qr: "Inserisci il tuo codice QR",
    continue: "Continua",
    buy: "Compra per 10 $",
    buy_link: "https://gumroad.com/l/wishclip",
    voice_title: "Come dovrebbe cantare il tuo clip?",
    ai_voice: "Voce IA",
    my_voice: "La mia voce",
    voice_prompt: "Registra 10-20 secondi di parlato o canto nella tua lingua: 'Ciao, sono Alex. Questa è una canzone per Masha!'",
    upload_voice: "Registra o carica la tua voce",
    voice_tip: "Puoi registrare la tua voce in qualsiasi lingua — kazaka, ucraina, armena, ecc. La canzone verrà creata nella tua lingua."
  }
};
